
[bot]
token = ""
listen-channel = 12345

[propresenter]
v = 6 # or 7
host = "127.0.0.1"
port = 55184
password = ""
batch-wait-time = 10
batch-max-count = 3
expire-time = 45
# propresenter 7 decided it doesnt need to send feedback for events, 
# so we have no way of knowing if someone presses hide, or if someone takes the screen manually.
# so for pro7, we'll just guess

[network] # retrieve credentials
target = ""
simpleauth-pass = ""